# Generated by Django 5.1.1 on 2024-09-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='myapp.store')),
            ],
            options={
                'unique_together': {('store', 'date', 'open_time', 'close_time')},
            },
        ),
    ]
