# Generated by Django 5.1.1 on 2024-09-19 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_transactionrequest_delete_approvalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
