# Generated by Django 5.1.1 on 2024-10-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrequest',
            name='storekeeper_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionrequest',
            name='user_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
