# Generated by Django 5.1.1 on 2024-10-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_transactionrequest_storekeeper_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
